name = "sequential-thinking"
version = "0.2.0"
homepage = "github.com"
creator = "jilebi"
contact = "support@jilebi.ai"

[resources]

[tools.sequential-thinking]
input_schema = { "type" = "object", "properties" = { "thought" = { "type" = "string", "description" = "Your current thinking step" }, "nextThoughtNeeded" = { "type" = "boolean", "description" = "Whether another thought step is needed" }, "thoughtNumber" = { "type" = "integer", "description" = "Current thought number", "minimum" = 1 }, "totalThoughts" = { "type" = "integer", "description" = "Estimated total thoughts needed", "minimum" = 1 }, "isRevision" = { "type" = "boolean", "description" = "Whether this revises previous thinking" }, "revisesThought" = { "type" = "integer", "description" = "Which thought is being reconsidered", "minimum" = 1 }, "branchFromThought" = { "type" = "integer", "description" = "Branching point thought number", "minimum" = 1 }, "branchId" = { "type" = "string", "description" = "Branch identifier" }, "needsMoreThoughts" = { "type" = "boolean", "description" = "If more thoughts are needed" } }, "required" = [
	"thought",
	"nextThoughtNeeded",
	"thoughtNumber",
	"totalThoughts",
] }
name = "sequential-thinking"
description = "A detailed tool for dynamic and reflective problem-solving through thoughts. This tool helps analyze problems through a flexible thinking process that can adapt and evolve. Each thought can build on, question, or revise previous insights as understanding deepens."
function = "sequential_thinking"
[tools.sequential-thinking.annotations]
title = "Sequential Thinking"
read_only_hint = false
destructive_hint = false
idempotent_hint = false
open_world_hint = true

[prompts]